# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy
# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

lang: pt-BR 
timezone: America/Sao_Paulo # Seu fuso horário
title: Leonardo S. Comandulli # Título que aparece no topo e na aba do navegador
tagline: AI & Engineering Solutions # Um subtítulo curto que aparece abaixo do seu nome
description: >- # Uma descrição mais longa para SEO (mecanismos de busca)
  A personal website and portfolio for Leonardo S. Comandulli, an AI & Engineering
  Solutions Developer focused on bridging the gap between industrial processes and
  modern technology.

# URL do site (IMPORTANTE para links funcionarem corretamente)
# Se o seu repositório for 'https://github.com/SEUNOME/SEUNOME.github.io',
# a url será 'https://SEUNOME.github.io' e a baseurl será '' (vazia).
url: "https://leocomandulli.github.io"
baseurl: "" # Deixe vazio se o repositório tiver o nome SEU-USUARIO-GITHUB.github.io

# -----------------------------------------------------------------------------
# Author Settings
# -----------------------------------------------------------------------------

author: Leonardo S. Comandulli
avatar: /assets/img/leocomandulli.jpg # Coloque a sua foto de perfil na pasta /assets/img/
email: leonardo.comandulli@gmail.com
location: Curitiba, PR, Brazil

# -----------------------------------------------------------------------------
# Social Links / Contatos
# -----------------------------------------------------------------------------

social:
  name: Leonardo S. Comandulli
  links:
    # Cole os links completos dos seus perfis
    - https://github.com/leocomandulli
    - https://www.linkedin.com/in/leonardocomandulli
    - https://medium.com/@leonardo.comandulli

# -----------------------------------------------------------------------------
# Configurações do Tema Chirpy
# -----------------------------------------------------------------------------

# A paleta de cores do site. Opções: 'auto', 'light', 'dark'
theme_mode: auto

# Configuração dos botões que aparecem no topo da página de perfil
profile:
  align: center # 'start', 'center', 'end'
  image:
    path: /assets/img/leocomandulli.jpg # Caminho para a foto de perfil
    alt: alt text for avatar # Texto alternativo para a imagem
  buttons:
    - name: Sobre Mim
      url: /about/ # Link para a sua página "Sobre Mim"
    - name: Projetos
      url: /projects/ # Link para uma página de projetos
    - name: Artigos
      url: /categories/articles/ # Link para a categoria de artigos do seu blog

# -----------------------------------------------------------------------------
# Seções Principais (Abas de Navegação)
# -----------------------------------------------------------------------------
# Estas são as abas que aparecerão no topo do site

tabs:
  - title: Home
    url: /
  - title: Sobre
    url: /about/
  - title: Blog
    url: /posts/
  - title: Categorias
    url: /categories/
  - title: Tags
    url: /tags/


  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
